;;; init --- Angel's init.el
;; config.el -- my Emacs Configuration. -*-lexical-binding: t-*-
;;
;; ⚠WARNING️⚠: This is not a good endorsement of me as a serious person.
;;
;; © 2024 Angel D. Campbell
;;   Licensed under a Creative Commons Attribution 4.0 International License.
;;   See http://creativecommons.org/licenses/by/4.0/
;;
;; Author: Angel D. Campbell <https://sr.ht/~perfect-angel/>
;; Maintainer: Angel D. Campbell
;; Created: December  26, 2024
;;
;; This file is not part of GNU Emacs.
;;
;; Do not edit this file, edit the config.org file which tangles
;; into this file
;;; Code:

(require 'package)
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives
	     '("nongnu" . "https://elpa.nongnu.org/nongnu/") t)
(package-initialize)

(require 'use-package)
(setq use-package-always-ensure t)

(use-package exec-path-from-shell ;; set path to shellpath
  :config
  (exec-path-from-shell-initialize))

(use-package emacs
  :config
  (setq auto-save-default nil ; don't autosave
	backup-directory-alist '(("." . "/tmp")) ; send backups to hell
	make-backup-files nil ; no backup files
	custom-file "~/.emacs.d/emacs-custom.el")) ; custom custom file

(when (display-graphic-p)
  (context-menu-mode 1)
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (horizontal-scroll-bar-mode -1)
  (setq visible-bell 1
	confirm-kill-emacs 'yes-or-no-p
	ring-bell-function 'ignore
	frame-inhibit-implied-resize t))



(use-package doom-themes)
(load-theme 'doom-gruvbox 1)
(set-frame-font "FiraCode Nerd Font 20" nil t)

(use-package all-the-icons)

(use-package mood-line
  ;; Enable mood-line
  :config
  (mood-line-mode)
  :custom
  (mood-line-glyph-alist mood-line-glyphs-fira-code))

(use-package dimmer
  :custom (dimmer-adjustment-mode :foreground))

(use-package dimmer
  :config
  (dimmer-configure-which-key)    ; Do not dim these special windows
  (dimmer-configure-hydra)
  (dimmer-configure-magit)

  (dimmer-mode t))

(use-package emojify)
(use-package nerd-icons)
(use-package rainbow-delimiters
  :hook ((prog-mode . rainbow-delimiters-mode)))

(use-package emacs
    :hook ((prog-mode . column-number-mode) ; columns
  	 (prog-mode . flymake-mode) ; checker
  	 ((prog-mode text-mode) . hs-minor-mode) ; folding
  	 ((prog-mode text-mode) . visual-line-mode) ; word wrap
  	 (prog-mode . auto-fill-mode))) ; auto word wrap

(use-package emacs
  :config
  (setq enable-recursive-minibuffers t ; i forgot why i do this
	tramp-default-method "ssh" ; faster tramp with ssh
	visual-fill-column-center-text t
	visual-fill-column-width 60)
  (setq-default fill-column 80) ; tty geezer
  (when (eq system-type 'darwin) ; mac specific settings
    (global-set-key [kp-delete] 'delete-char)) ; fix mac delete
  (electric-pair-mode 1) ; auto-pair
  (electric-indent-mode 1) ; auto-indent
  (fset 'yes-or-no-p 'y-or-n-p) ; 2 lazy 2 type yes
  (recentf-mode 1) ; what was i doing?
  (show-paren-mode 1) ; i believe in symmetry
  (global-eldoc-mode 1)) ; global documentation

(use-package evil ; evil
  :custom
  (evil-want-integration t)
  (evil-want-C-u-scroll 1)
  (evil-undo-system 'undo-redo)

  :config
  (evil-mode 1)
  (evil-set-leader nil (kbd "SPC"))
  (evil-set-leader nil "," t)
  (evil-define-key 'normal 'global
    (kbd "K") 'eldoc-box-help-at-point

    (kbd "<localleader>f") 'eglot-format-buffer
    (kbd "<localleader>r") 'eglot-rename
    (kbd "<localleader>a") 'eglot-code-actions

    (kbd "gd") 'xref-find-definitions

    (kbd "!") 'execute-extended-command
    (kbd "-") 'dired

    (kbd "<leader>/") 'counsel-ag
    (kbd "<leader>,") 'execute-extended-command
    (kbd "<leader>a") 'vterm
    (kbd "<leader>b") 'switch-to-buffer
    (kbd "<leader>d") 'project-dired
    (kbd "<leader>e") 'find-file
    (kbd "<leader>f") 'project-find-file
    (kbd "<leader>g") 'magit
    (kbd "<leader>h") 'describe-symbol
    (kbd "<leader>jp") 'angel/widen-prev-narrow
    (kbd "<leader>jn") 'angel/widen-next-narrow
    (kbd "<leader>js") 'counsel-outline
    (kbd "<leader>jc") 'org-capture
    (kbd "<leader>ja") 'org-agenda
    (kbd "<leader>k") 'delete-window
    (kbd "<leader>ll") 'flymake-show-buffer-diagnostics
    (kbd "<leader>lp") 'flymake-goto-prev-error
    (kbd "<leader>ln") 'flymake-goto-next-error
    (kbd "<leader>m") 'recentf
    (kbd "<leader>n") 'tab-new
    (kbd "<leader>q") 'save-buffers-kill-terminal
    (kbd "<leader>r") 'isearch-forward
    (kbd "<leader>sh") 'split-window-horizontally
    (kbd "<leader>sj") (lambda () (interactive)
			   (split-window-below)
			   (windmove-down))
    (kbd "<leader>sk") 'split-window-vertically
    (kbd "<leader>sl") (lambda () (interactive)
			   (split-window-right)
			   (windmove-right))
    (kbd "<leader>t") 'test-approximate
    (kbd "<leader>u") 'visual-fill-column-mode
    (kbd "<leader>vv") (lambda () (interactive) (find-file "~/dotfiles/config.org"))
    (kbd "<leader>w") 'save-buffer
    (kbd "<leader>x") 'xwidget-webkit-browse-url
    (kbd "<leader>y") 'yas-visit-snippet-file
    (kbd "<leader>zc") 'hs-hide-all
    (kbd "<leader>zo") 'hs-show-all))
(use-package evil-commentary
  :config
  (evil-commentary-mode))
(use-package evil-surround
  :config
  (global-evil-surround-mode))
(use-package evil-org
  :after org
  :hook ((org-mode . evil-org-mode))
  :config
  (require 'evil-org-agenda)
  (evil-org-agenda-set-keys))

(use-package which-key
  :custom
  (which-key-show-early-on-C-h t)
  (which-key-idle-delay 0.5)
  :config
  (which-key-mode 1))
(use-package eldoc-box)

(use-package avy)
(use-package counsel
  :custom
  (ivy-use-virtual-buffers t)
  (ivy-count-format "(%d/%d) ")
  :config
  (ivy-mode 1))

(use-package company
  :config
  (global-company-mode 1)) ;; replace with complete?

(use-package handlebars-mode)
      (use-package geiser-guile)
      (use-package emmet-mode
        :config
        (add-hook 'sgml-mode-hook 'emmet-mode) ;; Auto-start on any markup modes
        (add-hook 'html-mode-hook 'emmet-mode) ;; Auto-start on any markup modes
        (add-hook 'html-ts-mode-hook 'emmet-mode) ;; Auto-start on any markup modes
	(add-hook 'css-mode-hook  'emmet-mode)) ;; enable Emmet's css abbreviation.

(use-package rust-ts-mode
        :mode ("\\.rs\\'" . rust-ts-mode))
      (use-package treesit-auto
        :custom
        (treesit-auto-install 'prompt)
        :config
        (treesit-auto-add-to-auto-mode-alist 'all)
        (global-treesit-auto-mode))
      (use-package rmsbolt)
      (use-package cider)

(use-package eglot
  :hook ((js-ts-mode  . eglot-ensure)
	   (typescript-ts-mode  . eglot-ensure)
	   (rust-ts-mode  . eglot-ensure))
  :config
  (add-to-list 'eglot-server-programs
		 '(handlebars-mode "ember-language-server")))

(use-package org
  :config
  (setq org-pretty-entities t
        org-hide-emphasis-markers t
        org-auto-align-tags nil
        org-tags-column 0
        org-ellipsis "⤵"                ; …, ➡, ⚡, ▼, ↴, , ∞, ⬎, ⤷, ⤵
        org-catch-invisible-edits 'show-and-error
	  org-image-actual-width  nil
        org-special-ctrl-a/e t ; Note: Need to get this working with Evil!
        org-src-fontify-natively t      ; Pretty code blocks
        org-agenda-breadcrumbs-separator " ❱ "))

(use-package org-appear
  :config
  (add-hook 'org-mode-hook 'org-appear-mode))

(use-package org
  :custom
  (org-babel-clojure-backend 'cider)
  (org-babel-load-languages
   '((emacs-lisp . t)
     (shell . t)
     (python . t)
     (clojure . t)
     (js . t)
     (ruby . t))))

(use-package org
  :custom
  (org-directory "~/org")
  (org-default-notes-file "refile.org")
  (org-agenda-files '("today.org" "refile.org"))
  (org-capture-templates
   '(("t" "Todo" entry (file "~/org/refile.org") "* TODO %?")
     ("j" "Journal" entry (file+olp+datetree "~/org/journal.org") "* %?"))))


(use-package kubernetes)

;; irc
(use-package emacs
  :config
  (setq rcirc-default-nick "perfect_angel" ; i've never even sinned
	  rcirc-track-minor-mode 1
	rcirc-server-alist
	'(("irc.libera.chat"
	   :channels ("#emacs" "##rust" "#guix")
	   :nick "perfect_angel"
	   :port 6697
	   :encryption tls))))

(use-package emacs
  :config
  (setq browse-url-browser-function 'xwidget-webkit-browse-url)) ; use xwidget to browse

(use-package savehist
  :config
  (savehist-mode))
(use-package magit) ; git gud
(use-package iedit) ; TODO: why do i have this? edit quickfix?
(use-package lingva)
(use-package vterm)
(use-package simple-httpd)
(use-package yasnippet
  :config
  (setq yasnippet-snippets-dir "~/dotfiles/snippets/")
  (yas-global-mode 1)
  (global-set-key (kbd "C-x C-y") 'company-yasnippet))
(use-package yasnippet-snippets)

(provide 'init)
;;; amen
;;; init.el ends here
